# Verdaccio Configuration

# Путь к хранилищу пакетов
storage: /verdaccio/storage

# Путь к плагинам
plugins: /verdaccio/plugins

# Порт и хост
listen: 0.0.0.0:4873

# Веб-интерфейс
web:
  title: Verdaccio Registry
  # logo: http://somedomain/somelogo.png
  # primary_color: "#4b5e40"
  # gravatar: true | false
  # scope: "@scope"
  # sort_packages: asc | desc
  darkMode: true
  # favicon: http://somedomain/favicon.ico | /path/favicon.ico

# Аутентификация
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: 1000

# Uplinks - внешние реестры
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

# Пакеты и их политики доступа
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

# Логирование
logs: { type: stdout, format: pretty, level: http }

# Экспериментальные функции
#experiments:
#  # support for npm token command
#  token: false
#  # enable tarball URL redirect for uplinks
#  tarball_url_redirect: false
#  # enable legacy search API
#  legacy_search: false
#  # enable search API
#  search: false

# https://verdaccio.org/docs/logger
#log settings
#logs:
#  - {type: stdout, format: pretty, level: trace}
#  - {type: file, path: /verdaccio/storage/verdaccio.log, level: info}
#  - {type: file, path: /verdaccio/storage/verdaccio-error.log, level: error}
