# Verdaccio Configuration

# Path to package storage
storage: /verdaccio/storage

# Path to plugins
plugins: /verdaccio/plugins

# Port and host
listen: 0.0.0.0:4873

# Web interface
web:
  enable: false
  title: Verdaccio Registry
  # logo: http://somedomain/somelogo.png
  # primary_color: "#4b5e40"
  # gravatar: true | false
  # scope: "@scope"
  # sort_packages: asc | desc
  # darkMode: true
  # favicon: http://somedomain/favicon.ico | /path/favicon.ico

# Authentication
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: 1000

# Uplinks - external registries
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

# Packages and their access policies
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

# Logging
logs: { type: stdout, format: pretty, level: http }

# Experimental features
#experiments:
#  # support for npm token command
#  token: false
#  # enable tarball URL redirect for uplinks
#  tarball_url_redirect: false
#  # enable legacy search API
#  legacy_search: false
#  # enable search API
#  search: false

# https://verdaccio.org/docs/logger
#log settings
#logs:
#  - {type: stdout, format: pretty, level: trace}
#  - {type: file, path: /verdaccio/storage/verdaccio.log, level: info}
#  - {type: file, path: /verdaccio/storage/verdaccio-error.log, level: error}
